### ISSUE TITLE
If downloading Yahoo data fails after max retries, save the partial result

### ISSUE THREAD

**Issue by jaapterwoerds** [councilofelders/opensignals#8]
I noticed that when downloading yahoo ticker data failed after a set of tickers, the successfully retrieved data is not saved. Especially with the Yahoo API, functionality to save the ticker data incrementally is essential. In this case the max retries is exceeded so it probably does not make sense to skip the particular ticker and move on with the next since it would probably fail too.

Please note the augmented logging is mine, I was trying to figure out if tqdm was broken 😄 

```
[nix-shell:~/workspace/numerai-signals]$ python opensignals_test.py 
INFO:opensignals.data.yahoo:Retrieving data for 0 tickers from the database
INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:opensignals.data.yahoo:Number of eligible tickers: 5334
INFO:opensignals.data.yahoo:Downloading missing data for 5334 tickers
INFO:opensignals.data.yahoo:download_tickers: # tickers 5334 start: 2002-12-01
INFO:opensignals.data.yahoo:downloaded data for: 002270.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 001120.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000370.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000270.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000720.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 001450.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 002790.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 002350.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000880.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000060.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 002320.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 001040.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000100.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000210.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 001680.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000080.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000120.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000810.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 001430.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 000660.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003670.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003230.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003410.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 004020.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003550.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 004000.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 004170.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003850.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005940.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 003490.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005610.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005880.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005830.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 004370.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005490.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005850.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005930.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005300.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 004990.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 005380.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006260.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006360.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 007070.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006400.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006280.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 007310.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006650.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 006800.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 008490.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 008770.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 009150.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 009420.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 010120.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 010140.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 010060.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 009240.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 009830.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 009540.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 007700.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 010130.KS 0 
INFO:opensignals.data.yahoo:downloaded data for: 010620.KS 0 
Traceback (most recent call last):
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/nix/store/lcm6qi612273hm48pbfma3026fdizcc0-python3-3.8.9/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x155ced5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/nix/store/biln18x93j7qrqnx3vrxaazj8glnfi9n-python3.8-urllib3-1.26.5/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/018250.KS?period1=1038697200&period2=1626040800&interval=1d&events=div%2Csplits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x155ced5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opensignals_test.py", line 25, in <module>
    main()
  File "opensignals_test.py", line 11, in main
    yahoo.download_data(db_dir)
  File "/nix/store/xh42xrzksihad16h99bzspx8016kla89-python3.8-opensignals-v0.0.1-rc5/lib/python3.8/site-packages/opensignals/data/yahoo.py", line 255, in download_data
    temp_df = download_tickers(tickers.split(' '), start=start_date)
  File "/nix/store/xh42xrzksihad16h99bzspx8016kla89-python3.8-opensignals-v0.0.1-rc5/lib/python3.8/site-packages/opensignals/data/yahoo.py", line 170, in download_tickers
    ticker, data = future.result()
  File "/nix/store/lcm6qi612273hm48pbfma3026fdizcc0-python3-3.8.9/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/nix/store/lcm6qi612273hm48pbfma3026fdizcc0-python3-3.8.9/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/nix/store/lcm6qi612273hm48pbfma3026fdizcc0-python3-3.8.9/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/xh42xrzksihad16h99bzspx8016kla89-python3.8-opensignals-v0.0.1-rc5/lib/python3.8/site-packages/opensignals/data/yahoo.py", line 188, in download_ticker
    data = requests.get(url=url, params=params)
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/1yvvvy5vz6sga37wmid70faq7q6yd82p-python3.8-requests-2.25.1/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/018250.KS?period1=1038697200&period2=1626040800&interval=1d&events=div%2Csplits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x155ced5e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))


```

**Comment by jrdi** [comment]
Update to the latest version. `opensignals` is not making calls to `query1.finance.yahoo.com` anymore.
